// src/crosswordData.js

const crosswordData = [
    [
        {
            answer: "NEELUMVALLY",
            hint: "Mini Switzerland of Pakistan.",
            startx: 2,
            starty: 8,
            orientation: "across",
            position: 1,
        },
        {
            answer: " KARAKORAM",
            hint: "Highest paved international road, connecting Pakistan to China.",
            startx: 9,
            starty: 1,
            orientation: "down",
            position: 2,
        },
        {
            answer: "SKARDU",
            hint: "Region in Gilgit-Baltistan known for its apricot orchards",
            startx: 3,
            starty: 11,
            orientation: "across",
            position: 3,
        },
        {
            answer: "KHYBERPASS",
            hint: "Mountain pass that connects Pakistan with Afghanistan",
            startx: 4,
            starty: 11,
            orientation: "down",
            position: 4,
        },
        {
            answer: "DERAWAR",
            hint: "Fortress in southern Punjab, known for its 40 massive bastions",
            startx: 12,
            starty: 7,
            orientation: "down",
            position: 5,
        },
        {
            answer: "GILGIT",
            hint: "Ancient caravanserai town on the Silk Road",
            startx: 16,
            starty: 2,
            orientation: "down",
            position: 6,
        },
        {
            answer: "THATTA",
            hint: "Home to the Shah Jahan Mosque",
            startx: 16,
            starty: 11,
            orientation: "across",
            position: 7,
        },
        {
            answer: "SHALIMAR",
            hint: "Historic garden complex built by Emperor Shah Jahan",
            startx: 17,
            starty: 10,
            orientation: "down",
            position: 8,
        },
        {
            answer: "CHITRAL",
            hint: "The valley with unique Kalash culture.",
            startx: 8,
            starty: 13,
            orientation: "down",
            position: 9,
        },
        {
            answer: "MULTAN",
            hint: "The ancient town in Punjab, known as the City of Saints",
            startx: 13,
            starty: 16,
            orientation: "across",
            position: 10,
        },
        {
            answer: "DAMANEKOH",
            hint: "Islamabad scenic hill station",
            startx: 22,
            starty: 1,
            orientation: "down",
            position: 12,
        },
        {
            answer: "FAISALMOSQUE",
            hint: "Islamabad scenic hill station",
            startx: 25,
            starty: 3,
            orientation: "down",
            position: 11,
        },
        {
            answer: "TAXILA",
            hint: "A plateau famous for its Buddhist monastic complexes",
            startx: 13,
            starty: 6,
            orientation: "across",
            position: 13,
        },
        {
            answer: "DEOSAIPLAINS",
            hint: "A plateau famous for its Buddhist monastic complexes",
            startx: 1,
            starty: 2,
            orientation: "across",
            position: 14,
        },
        {
            answer: "HARAPPA",
            hint: "Ancient trading city along the Silk Road",
            startx: 6,
            starty: 17,
            orientation: "across",
            position: 15,
        },
        {
            answer: "KAGHAN",
            hint: "Lush northern valley known for its trout-rich rivers",
            startx: 18,
            starty: 2,
            orientation: "down",
            position: 16,
        }, 


{
            answer: "SHIMSHAL",
            hint: "Highest village in Pakistan, located in Gilgit-Baltistan",
            startx: 17,
            starty: 18,
            orientation: "across",
            position: 17,
        },
        {
            answer: "MURREE",
            hint: "Famous British-era hill station",
            startx: 2,
            starty: 4,
            orientation: "across",
            position: 18,
        },
        {
            answer: "KHAIRPUR",
            hint: "Historical town in Sindh known for its forts, mosques",
            startx: 14,
            starty: 10,
            orientation: "down",
            position: 19,
        },
        {
            answer: "HINGOL",
            hint: "Saltwater lake in Balochistan",
            startx: 24,
            starty: 10,
            orientation: "down",
            position: 20,
        },
        {
            answer: "LAHORE",
            hint: "City of Gardens",
            startx: 12,
            starty: 20,
            orientation: "across",
            position: 21,
        },
        {
            answer: "NANGAPARBAT",
            hint: "Northern peak in Gilgit-Baltistan",
            startx: 1,
            starty: 10,
            orientation: "down",
            position: 22,
        },
        {
            answer: "SAWAT",
            hint: "A town in Khyber Pakhtunkhwa ",
            startx: 20,
            starty: 2,
            orientation: "down",
            position: 23,
        },

 
       
    ],
    [
        {
            answer: "JHELUM",
            hint: "River that forms the western border of the Punjab ",
            startx: 4,
            starty: 1,
            orientation: "across",
            position: 1,
        },
        {
            answer: "MOHENJODARO",
            hint: "Ancient ruins near Harappa",
            startx: 9,
            starty: 1,
            orientation: "down",
            position: 2,
        },
        {
            answer: "JASMINE",
            hint: "National flower of Pakistan",
            startx: 16,
            starty: 4,
            orientation: "across",
            position: 3,
        },
        {
            answer: "INDUS",
            hint: "River that flows through Punjab ",
            startx: 20,
            starty: 4,
            orientation: "down",
            position: 4,
        },
        {
            answer: "CHOLISTAN",
            hint: "Desert festival in Punjab",
            startx: 13,
            starty: 12,
            orientation: "across",
            position: 5,
        },
        {
            answer: "SHALIMAR",
            hint: "Famous Mughal-era garden in Lahore",
            startx: 3,
            starty: 7,
            orientation: "down",
            position: 6,
        },
        {
            answer: "RUPEE",
            hint: "Pakistani currency.",
            startx: 5,
            starty: 4,
            orientation: "across",
            position: 7,
        },
        {
            answer: "MANCHAR",
            hint: "The largest freshwater lake in Pakistan",
            startx: 11,
            starty: 14,
            orientation: "down",
            position: 8,
        },
        {
            answer: "HUNZA",
            hint: "A valley in Gilgit-Baltistan known for apricots",
            startx: 12,
            starty: 2,
            orientation: "across",
            position: 9,
        },
        {
            answer: "MARKHOR",
            hint: "Pakistan’s national animal.",
            startx: 15,
            starty: 7,
            orientation: "down",
            position: 10,
        },
        {
            answer: "FAISALABAD",
            hint: "City known as the 'Manchester of Pakistan' for its textile industry",
            startx: 24,
            starty: 7,
            orientation: "down",
            position: 11,
        },
        {
            answer: "THAR",
            hint: "Desert region shared by Pakistan and India.",
            startx: 22,
            starty: 11,
            orientation: "across",
            position: 12,
        },
        {
            answer: "BADSHAHI",
            hint: "A white marble Mughal-era mosque in Lahore",
            startx: 2,
            starty: 17,
            orientation: "across",
            position: 13,
        },
        {
            answer: "BASANT",
            hint: "Annual harvest festival in the Punjab region ",
            startx: 20,
            starty: 11,
            orientation: "down",
            position: 14,
        },
        {
            answer: "ATTABAD",
            hint: "Large freshwater lake in Gilgit-Baltistan ",
            startx: 15,
            starty: 19,
            orientation: "across",
            position: 15,
        },
        {
            answer: "AJRAK",
            hint: "Colorful handmade textile worn by women in Sindh.",
            startx: 9,
            starty: 20,
            orientation: "across",
            position: 16,
        },
        {
            answer: "ZIARAT",
            hint: "Mountainous area in Balochistan with scenic views and cultural heritage",
            startx: 6,
            starty: 9,
            orientation: "down",
            position: 17,
        },
        {
            answer: "KHAIRPUR",
            hint: "Historical city in Sindh known for its cultural heritage and forts.",
            startx: 12,
            starty: 4,
            orientation: "down",
            position: 18,
        },
        {
            answer: "NOORMAHAL",
            hint: "A historic garden complex built by the Mughal emperor Humayun.",
            startx: 1,
            starty: 3,
            orientation: "down",
            position: 19,
        },
        {
            answer: "RABAB",
            hint: "Traditional Pakistani instrument similar to a lute.",
            startx: 2,
            starty: 15,
            orientation: "down",
            position: 20,
        },
        {
            answer: "SIACHEN",
            hint: "Traditional Pakistani instrument similar to a lute.",
            startx: 9,
            starty: 15,
            orientation: "across",
            position: 21,
        },
        {
            answer: "SEHWAN",
            hint: "Largest glacier outside polar regions, in the Karakoram range.",
            startx: 19,
            starty: 2,
            orientation: "across",
            position: 22,
        },
    ],
];

export default crosswordData;
